### ISSUE TITLE
PPS does not work ... 

### ISSUE THREAD

**Issue by kbahey** [hjd1964/OnStepX#10]
I enabled PPS using the new syntax.

 #define TIME_LOCATION_PPS_SENSE HIGH

This is on an F303CC Blue Pill with the DS3231 and the 1Hz pin wired in.

But I don't see PPS on the SWS status page. 

Would using LOW make a difference here?

**Comment by hjd1964** [comment]
PPS was working... just the status wasn't indicating it.  Old #define from OnStep looking of == ON where the new settings are HIGH, LOW, BOTH, or OFF was excluding the provision for PPS status return.
