### ISSUE TITLE
Compile Errors due to typos

### ISSUE THREAD

**Issue by azwing** [hjd1964/OnStepX#13]
Hope to help with these

diff --git a/src/plugins/sample/Sample.h b/src/plugins/sample/Sample.h
index 54e5298..9f2a7e3 100644
--- a/src/plugins/sample/Sample.h
+++ b/src/plugins/sample/Sample.h
@@ -1,5 +1,5 @@
 // Sample plugin
-#pragma onced
+#pragma once
 
 class Sample {
 public:
diff --git a/src/telescope/Telescope.command.cpp b/src/telescope/Telescope.command.cpp
index 54ffecf..74ffcbb 100644
--- a/src/telescope/Telescope.command.cpp
+++ b/src/telescope/Telescope.command.cpp
@@ -61,20 +61,20 @@ bool Telescope::command(char reply[], char command[], char parameter[], bool *su
   #endif
 
   //  B - Reticule/Accessory Control
-  // :B+#       Increase reticule Brightness
+  // :B+#       Increase reticle Brightness
   //            Returns: Nothing
   // :B-#       Decrease Reticule Brightness
   //            Returns: Nothing
   if (command[0] == 'B' && (command[1] == '+' || command[1] == '-') && parameter[0] == 0)  {
     #if RETICLE_LED_DEFAULT >= 0 && RETICLE_LED_PIN != OFF
       int scale;
-      if (reticuleBrightness > 255-8) scale = 1; else
-      if (reticuleBrightness > 255-32) scale = 4; else
-      if (reticuleBrightness > 255-64) scale = 12; else
-      if (reticuleBrightness > 255-128) scale = 32; else scale = 64;
-      if (command[1] == '-') reticuleBrightness += scale;  if (reticuleBrightness > 255) reticuleBrightness = 255;
-      if (command[1] == '+') reticuleBrightness -= scale;  if (reticuleBrightness < 0)   reticuleBrightness = 0;
-      analogWrite(RETICLE_LED_PIN, analog8BitToAnalogRange(reticuleBrightness));
+      if (reticleBrightness > 255-8) scale = 1; else
+      if (reticleBrightness > 255-32) scale = 4; else
+      if (reticleBrightness > 255-64) scale = 12; else
+      if (reticleBrightness > 255-128) scale = 32; else scale = 64;
+      if (command[1] == '-') reticleBrightness += scale;  if (reticleBrightness > 255) reticleBrightness = 255;
+      if (command[1] == '+') reticleBrightness -= scale;  if (reticleBrightness < 0)   reticleBrightness = 0;
+      analogWrite(RETICLE_LED_PIN, analog8BitToAnalogRange(reticleBrightness));
       #if RETICLE_LED_MEMORY == ON
         nv.write(NV_TELESCOPE_SETTINGS_BASE, reticleBrightness);
       #endif

**Comment by hjd1964** [comment]
Think that should be taken care of now, thanks.
