### ISSUE TITLE
Any interest on migrating to PlatformIO and have automated CI/CD check on github?

### ISSUE THREAD

**Issue by simonachmueller** [hjd1964/OnStepX#22]
Hello,

Yesterday I finished the hardware for OnStep (ESP32) controller and tried to build OnStepX for it. I used my favorite development tool [PlatformIO](https://platformio.org/) (I don't have any relations to this company) to convert the Arduino project into PlatformIO project. It went without any trouble, I was able to build OnStepX with Visual Studio Code (PlatformIO is a plugin for VS Code).

I thought it could be beneficial for the OnStep project to migrate to PlatformIO for at least 2 reasons:
1. It's much nicer to develop in Visual Studio Code with all the color formatting, suggestions etc. then in Arduino IDE (IMO)
2. PlatformIO offers a CLI (command line interface) tool to build the project and can be integrated in automated build pipelines.

Regarding the 2., you can see an example in one of my ESP32 projects here [ESP32Focuser](https://github.com/simonachmueller/ESP32Focuser). It uses Arduino platform and I developed it using PlatformIO and integrated into the Github Actions.

I configured it such a way, that every commit will be automatically build on Github cloud build agents, which is for free, and you will see if the build is successful or not (red cross or green check mark):
![image](https://user-images.githubusercontent.com/3511513/170053137-0575c2df-7415-423f-a008-6cdf48983ee8.png)

From what I know you would be able to develop both in VSCode with PlatformIO and Arduino IDE after that, but the build with Arduino would not be automatically checked (so it could be a case that the build on Github is successful, but locally you can't build with Arduino IDE because of some build errors).

Are you interested on this? If yes, I can help you by creating a pull request with the migration files and build pipeline configuration.

**Comment by hjd1964** [comment]
Probably not something I'd be interested in presently, I get the feeling it'd require more time and effort and the benefits would be minimal.

If the simple (easy for users) Arduino IDE starts to be phased in favor of that Eclipse based abomination it might still happen though.

Note that OnStepX has been an VSC project from day one, I just compile in the Arduino IDE.

**Comment by hjd1964** [comment]
Never mind about Eclipse thing, must have been an plug-in I got a look at a while back, thought it was an official beta or something. That doesn't appear to be the case (a good thing!)

**Comment by davidusb-geek** [comment]
Supporting this would have been great!
Not only for PlatformIO but also for the CI/CD functionality.
Right now I'm updating to OnStepX from Onstep4.2 and I have just begun banging my head with these Arduino libraries. While PlatformIO deals with this automatically.
As CI/CD these are just powerful tools for software developement. I'm a current maintainer of my of Python package and without these github workflow the code maintenance would be really harder...

**Comment by davidusb-geek** [comment]
Anyway @simonachmueller, would it be possible to fork this repo and setup that PlatformIO functionnality?
No need to merge if @hjd1964 doesn't wants to, but that fork could help a lot of people out there.

**Comment by rchadgray** [comment]
I dont see how Platform IO will help any new user to the Project.  Most users come into OnStep and they have to learn electronics, mechanical and software programming.  It is already a very steep learning curve.  Using the Arduino IDE puts a software interface on the project that people can understand a little bit easier.  For the advanced users and your own personal project sure... fork and move on. I dont see platformIO being a solution for the people that the project is targeting.
