### ISSUE TITLE
Issue with custom slew rate per axis (seems to be a simple fix)

### ISSUE THREAD

**Issue by simonachmueller** [hjd1964/OnStepX#26]
In this [thread](https://onstep.groups.io/g/main/topic/7725169) was mentioned that slew rate can be set per axis separately (satellite tracking use case).

It seems to be a problem in the Guide.cpp` startAxis1(...)` and `startAxis2(...)`, where `rateSelectToRate(GuideRateSelect rateSelect, uint8_t axis)` method is called without sending a second optional argument (axis), which forces the logic to use the slew rate from the axis1 for both axes.

Changing it to `float rate = rateSelectToRate(rateSelect, 1);` in startAxis1() and `float rate = rateSelectToRate(rateSelect, 2);` in startAxis2() fixes the problem.

**Comment by hjd1964** [comment]
Agree, that was a bug. Thanks.
