### ISSUE TITLE
Typo causing compilation failure

### ISSUE THREAD

**Issue by LuckyEddie47** [hjd1964/OnStepX#31]
In OnStepX/src/lib/encoder/Encoder.h

Line 4
#include "../../common.h"
should be
#include "../../**C**ommon.h"

This caused failure to compile on using the Arduino IDE V2.0.0 on 64-bit Raspberry Pi OS. Correcting the case of the include as shown above fixed that error.

**Comment by hjd1964** [comment]
Thanks, should be taken care of now.
