### ISSUE TITLE
compilation errors and warnings

### ISSUE THREAD

**Issue by azwing** [hjd1964/OnStepX#4]
If it can help improve ...

**1) by defining PEC_STEPS_PER_WORM_ROTATION different from 0 I get the following compilation errors**
/home/alain/Development/OnStepX/src/telescope/mount/pec/Pec.cpp: In member function 'void Pec::poll()':
/home/alain/Development/OnStepX/src/telescope/mount/pec/Pec.cpp:117:18: error: 'stepsPerSiderealSecondAxis1' was not declared in this scope
       if (dist > stepsPerSiderealSecondAxis1*60.0 && wormIndexState != lastState && wormIndexState == true) {
                  ^
/home/alain/Development/OnStepX/src/telescope/mount/pec/Pec.cpp:125:46: error: 'stepsPerSiderealSecondAxis1' was not declared in this scope
       if (wormIndexSenseThisSecond && dist > stepsPerSiderealSecondAxis1) wormIndexSenseThisSecond = false;
                                              ^
Erreur de compilation pour la carte Teensy 3.5
 
**2) Redefining handle most probably a typo in here**
void tasksMonitor() {
  uint8_t handle = tasks.getFirstHandle();
  for (int i = 0; i < TASKS_MAX; i++) {
    if (handle == 0) break;
    tasks.refreshPeriod(handle);
//    **uint8_t** handle = tasks.getNextHandle();
    handle = tasks.getNextHandle();
  }
}

**Comment by hjd1964** [comment]
Thanks for pointing those out, should be taken care of now.
