### ISSUE TITLE
Status LED doesn't reflect motor fault.

### ISSUE THREAD

**Issue by mike-s123** [hjd1964/OnStepX#47]
OnStep10.18c, Smart Web Server 2.06j 

I'm beginning a MaxPCB4 build. Both Teensy4.1 and WeMos D1 Mini Pro (SWS) are installed, running, and communicating. But no motor drivers yet. Relevant config:

```
#define STATUS_LED                    ON //    OFF, Steady illumination if no error, blinks w/error code otherwise.          Option
#define AXIS1_DRIVER_MODEL            TMC5160 //    OFF, Enter motor driver model (above) in both axes to activate the mount.    <-Often
#define AXIS1_DRIVER_STATUS           ON //    OFF, ON, HIGH, or LOW.  For driver status info/fault detection.               Option
#define AXIS2_DRIVER_MODEL            TMC5160 //    OFF, Enter motor driver model (above) in both axes to activate the mount.    <-Often
#define AXIS2_DRIVER_STATUS           ON //    OFF, ON, HIGH, or LOW.  Polling for driver status info/fault detection.       Option
#define STATUS_MOUNT_LED              OFF //    OFF, ON Flashes proportional to rate of movement or solid on for slews.       Option

```
Because the TMC5160 drivers are not installed, SWS correctly reports "Driver Status: Comms failure (Fault)" for both axes. According to the Wiki ( https://onstep.groups.io/g/main/wiki/30067#STATUS_LED ), the status LED should blink 4 times per cycle if a motor driver initialization error was detected. It does not, it illuminates steadily beginning a few seconds after power up. 

Guessing the code may only set the status LED if it receives an error from the stepper controller, but doesn't if it's unable to communicate with the controller. It should.

**Comment by hjd1964** [comment]
From a design standpoint successful motor driver initialization does not depend on the driver status being present.  If at some point that changes this behavior might change but until then this should be considered normal behavior.
