### ISSUE TITLE
Tracking status

### ISSUE THREAD

**Issue by EZT-Test** [hjd1964/OnStepX#49]
Hello,
I think there is an issue with checking the tracking status inside Status.command.cpp.
if (mount.isTracking())                  reply[i++] = 'N'; else reply[i++] = 'T';
The above code should be changed as below,
if (!mount.isTracking())                  reply[i++] = 'N'; else reply[i++] = 'T';
Thanks.
Phil

**Comment by hjd1964** [comment]
Taken care of, thanks.
