### ISSUE TITLE
:GX96 processing

### ISSUE THREAD

**Issue by azwing** [hjd1964/OnStepX#5]
In file "Goto.command.cpp"

I believe it should be
case '6': reply[0] = "EWB"[preferredPierSide - **1**]; reply[1] = 0; break; // preferred pier side
instead of 
case '6': reply[0] = "EWB"[preferredPierSide - **10**]; reply[1] = 0; break; // preferred pier side

Maybe I did not understand the code but at east for me it works, I receive the correct reply

Regards

**Comment by hjd1964** [comment]
No idea why I put 10 in there, agree should be 1.

Thanks.
