### ISSUE TITLE
 case-sensitive filesystem handling on  unix

### ISSUE THREAD

**Issue by beigenmann** [hjd1964/OnStepX#53]
--- a/src/lib/axis/motor/servo/filters/rolling.cpp
+++ b/src/lib/axis/motor/servo/filters/rolling.cpp
@@ -1,7 +1,7 @@
 // -----------------------------------------------------------------------------------
 // rolling average filter
 
-#include "Rolling.h"
+#include "rolling.h"

--- a/src/lib/axis/motor/servo/filters/windowing.cpp
+++ b/src/lib/axis/motor/servo/filters/windowing.cpp
@@ -1,7 +1,7 @@
 // -----------------------------------------------------------------------------------
 // windowing average filter
 
-#include "Windowing.h"
+#include "windowing.h"

**Comment by hjd1964** [comment]
Thanks... that's such a pain but should be good now.
