### ISSUE TITLE
Using NTP as time source

### ISSUE THREAD

**Issue by beigenmann** [hjd1964/OnStepX#54]
+++ b/src/telescope/mount/site/Site.cpp
@@ -93,10 +93,10 @@ IRAM_ATTR void clockTickWrapper() { fracLAST++; }
 
 #if TIME_LOCATION_SOURCE == NTP
   void ntpCheck() {
-    if (tls->isReady()) {
+    if (site.tls->isReady()) {
       VLF("MSG: Mount, setting date/time from NTP");
       JulianDate jd;
-      tls->get(jd);
+      site.tls->get(jd);

**Comment by hjd1964** [comment]
Missed that one, patched now, thanks.
