### ISSUE TITLE
Isses with MaxESP3 (PPS, SWS GPIO)

### ISSUE THREAD

**Issue by vzr314** [hjd1964/OnStepX#56]
New findings shown that this issue is actually related to ESP32 library version. I use MaxESP3 with 2.0.0 and MaxESP4 with 2.0.14 and these are issues I found:

With ESP32 board version 2.0.0:
PPS not working
SWS as a GPIO device compiles (didn't tested if it actually works)

With ESP32 board version 2.0.14:
PPS is working (only with PPS sense set to LOW)
When SWS is set as a GPIO device it doesn't compile at all (throwing an error)

**Comment by hjd1964** [comment]
I don't believe there is an issue here other than misconfiguration.
