### ISSUE TITLE
Bluetooth is not available

### ISSUE THREAD

**Issue by mcvall** [hjd1964/OnStepX#59]
In the last version of OnStepX it was possible to connect via bluetooth. Namely in "Extended.config" (#define SERIAL_BT_MODE SLAVE // OFF, use SLAVE to enable the interface (ESP32 only).
In the new version OnStep10.23f it is not there.

**Comment by vzr314** [comment]
Bluetooth configuration is moved from Extended.config.h to Config.h for quiet some time. Please check following line:

https://github.com/hjd1964/OnStepX/blob/main/Config.h#L29

**Comment by mcvall** [comment]
Thanks!
