### ISSUE TITLE
SyncEnc :SX42,1# issue with OnStepX OnStep10.20a

### ISSUE THREAD

**Issue by toups** [hjd1964/OnStepX#60]
:SX42,1# is not successfully completing and won't sync properly.

Potential solution via programming via analogy.  Assume the same conditions should be used for :SX42,1# as used in  :SX44,12.34,9.876#

Line numbers are from release OnStepX-10.20a.zip.

In src/telescope/mount/Mount.command.cpp line 233 which was
                if (e != CE_NONE) { *commandError = e; return true; }
should be replaced with
                if (e != CE_NONE && e != CE_SLEW_ERR_IN_STANDBY && e != CE_SLEW_IN_SLEW) { *commandError = e; return true; }
assuming line 255 is correct.

Also, I assume that line 235 which is
              if (isnan(encoderAxis1) || isnan(encoderAxis2) || syncFromOnStepToEncoders) { *commandError = CE_0; return true; }
should be replaced with
            if ( isnan(encoderAxis1) ||
                 isnan(encoderAxis2) ||
                 syncFromOnStepToEncoders ||
                 (goTo.state != GS_NONE && goTo.stage != GG_NEAR_DESTINATION_WAIT) ||
                  guide.state != GU_NONE) { *commandError = CE_0; return true; }
Assuming that lines 258-262 are correct.  Although this check was not causing my issue I assume the extra conditions are probably needed.

I have tried this on my local build and it does seem to resolve the initial issue.

**Comment by hjd1964** [comment]
The #SX0, #SX1, and #SX2 commands are considered obsolete and have been removed from the latest OnStepX.
