### ISSUE TITLE
compile Teensy 4.1 error  

### ISSUE THREAD

**Issue by ezioall59** [hjd1964/OnStepX#67]
hi
compiling with Arduino 1.8.9 I get this very strange error.
the missing file is present
why this error??
I also tried with another laptop both on Fedora and windows 10
it always gives me this error
even changing the PINMAP example ESP32 always the same error
I don't know where to put my hands

hardware/teensy/avr/libraries/SPI -I/home/ezio/Arduino/libraries/Adafruit_Sensor-1.1.7 /tmp/arduino_build_398211/sketch/src/plugins/sample/Sample.cpp -o /dev/null
Alternatives for ..\..\lib\commands\CommandErrors.h: []
ResolveLibrary(..\..\lib\commands\CommandErrors.h)
  -> candidates: []
In file included from /home/ezio/Arduino/OnStepX/src/plugins/sample/Sample.cpp:3:
Più di una libreria trovata per "TimeLib.h"
/home/ezio/Arduino/OnStepX/src/plugins/sample/Sample.h:4:10: fatal error: ..\..\lib\commands\CommandErrors.h: No such file or directory
Usata: /home/ezio/Arduino/libraries/Time-1.6.1
    4 | #include "..\..\lib\commands\CommandErrors.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by papadako** [comment]
Can you please check the following?

https://github.com/hjd1964/OnStepX/pull/69

**Comment by ezioall59** [comment]
hi
i tried from windows 10
first from a folder already unzipped and it doesn't work, while unzipping directly from window works
so for a strange reason from Fedora 41 it doesn't work
so i close this problem
the cause is not in OnStepX
