### ISSUE TITLE
every thing looks good BUT first goto is always a mess

### ISSUE THREAD

**Issue by arakeis** [hjd1964/OnStepX#68]
Hi all,

I love this project and yet can't get it to work...

OnStepX 10.24c
link to drive with config files and shot of mount in "off" positions
[https://drive.google.com/drive/folders/1fdDdutSKpvgrhDIlCx1_RB_TPJ3z0ozE?usp=sharing]

Here is my gear :
1. mount is a german equatorial DIY strain wave 
2. board is the minipcb2 version
3. using onstep android app for the time being (over wifi)

I trie to achieve a simple test, get my mount to "roughly" point to a specific bright star.

Here is my process : 

1. everything is connected and powered on
2. scope is physically pointing to the NCP
3. open app
4. Set position with "Observing sites -> Use Curent Location + upload"
5. Set time with "Set Date/Time"
6. Unpark

At this point, juste to be sure, I make a "Un Park / At Home (reset)/ Un Park"

7. goto Kocab, at the current time : +13az +63alt (little bit up and right from the NCP). (J2000:	14h 50m 42s	 74° 09' 20")
(obviously using the J2000 coordinates on the manual goto interface)
8. the mounts is pointing no where near the correct position, the RA axis seems the most off position --> see pic (link above)
9. goto Home
10. back home, right on spot, so mechanically the mount is ok
11. heading to the SWS to reverse the RA axis -> reboot to upload
12. redo everything with the RA reversed from 1. to 7.
13. still not right  --> see pic (link above)
14. let's reverse the DEC axis
15. heading to the SWS to reverse the DEC axis -> reboot to upload
16. redo everything with the RA and DEC reversed from 1. to 7.
17. still not right -> same position as 8.  --> see pic (link above)

my steps per degrees are fine, microsteps as well, I still dont get what is wrong in my setup...

Any clue would be greatly appreciated !

**Comment by arakeis** [comment]
Wrong place will post it in newsletter

**Comment by hjd1964** [comment]
Good idea :)
